language: node_js

cache: npm

node_js:
  - "8"
  - "10"
  - "12"

branches:
  only:
    - master

notifications:
  email: false

after_success:
  - if [[ $(node -v) == v10* ]]; then npm install coveralls; ./node_modules/.bin/coveralls < coverage/lcov.info; fi
